baseURL = 'https://via-zhang.github.io/qgis'
title = 'QGIS Activities'
theme = 'hugo-theme-relearn'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'QGIS Activities'
    weight = 1

  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    title = 'Actividades QGIS'
    weight = 2

[params]
  themeVariant = ['blue', 'zen-dark']
  hideAuthorDate = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'